apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: argo-combined-demo/argo-workflows/overlays/production
    repoURL: https://github.com/sarsatis/devops-tools.git
    targetRevision: HEAD
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

