apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-workflows
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: argo-combined-demo/jenkins-workflows/overlays/production
    repoURL: https://github.com/sarsatis/devops-tools.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
