apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCYfphVvS7QLs0hgrOAcEzCXq7qzRMyDyG8akOZFou0NzQe1UQmebz97FHXlZufL8rLCL88Kq+f0klFooB0lafX0+mMFkzOAh42X2Iz1q6EKAW6dfa6ipYQuvPnBO9H3bkgxdsh8DdWq64zK7flwqyk/FZY/LG/Nd45dEc/kMPcrbzNvk8GS9pWRtEmupT4rvrDTyncz8d5DYb28mgClM6HoPJXGIUw79XCm3rXS7fdAdtMiC43cf//lqA6wMSSVc3FCvkfgvAu0ku2igeczCVIWbp9QVWamniH1XuHJYTtsNWm+5nHMOCvwQDRzAUUDFdHbiT86CWtoUbAShlZujBEr0+h44tpMKBnL15NGgVHutyr3MFkBFnI1qZJ5FMXYuP+d0qUrh6A9RZzyBJdgxvwy6T6WUybJ4rTGGQSe9UfnwjWcji7UYZH/MEcaxLG2DxBes5oHmEQE38ZOJVKonWgM+LtmrKZx/Zd0awfKl+KaUJ8dBDDBqpPg4cQ4zQtL1fgmaY8RCmCR8Lj4XS8RYwcsQrhkMh9Jq7hlcsBhc8/Iu19gvc4SOf2KjJmKfTKNHuSQUUqyoM4KOIFFR2DA5BsNE5DMwusAXHpzhB92PABmemP/PlR6HYJnmpk72qO3ISFpa8eAElYlXoBLgXQtlQQE/lDvUip+k073QU3gFft1OHHKjCXY3J5MI5fHL4+tZvF7oy1KdVfnAE+pqycSgXU9hRxi4zSdNtjLvC57YIHvm1TnZ47Ex9Y
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

