apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: github
    eventSourceName: github
    eventName: argo-combined-app
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: argo-combined-app-
              namespace: workflows
            spec:
              entrypoint: whalesay          # invoke the whalesay template
              templates:
                - name: whalesay              # name of the template
                  container:
                    image: docker/whalesay
                    command: [ cowsay ]
                    args: [ "hello world" ]
                    resources: # limit the resources
                      limits:
                        memory: 32Mi
                        cpu: 100m
              